 const books={
    booksInfo:[
        {
            name:'Maths',
            author:'R S Aggarwal',
            price:350,
            class:'VII',
            image:'/images/rsvi.jpg',
            brand:'Bharti Bhawan',
            InStock:100,
            rating:4.8,
            reviews:168,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
        {
           name:'Maths',
           author:'R S Aggarwal',
           price:380,
           class:'VII',
           image:'/images/rsvii.jpg',
           brand:'Bharti Bhawan',
           InStock:200,
           rating:4.8,
           reviews:168,
           description: 'Well Organised Mathematicals concepts and it covers basics to advance level',

        },
        {
            name:'Maths',
            author:'R S Aggarwal',
            price:420,
            class:'VIII',
            image:'/images/rsviii.jpg',
            brand:'Bharti Bhawan',
            InStock:200,
            rating:4.8,
            reviews:168,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
        {
            name:'Maths',
            author:'R D Sharma',
            price:350,
            class:'VI',
            image:'/images/rdvi.jpg',
            brand:'Dhanpat Rai Publications',
            InStock:0,
            rating:5,
            reviews:48,
            description: 'Basically for advance level with more questions practices',
 
         },
         {
            name:'Maths',
            author:'R D Sharma',
            price:400,
            class:'VII',
            image:'/images/rdvii.jpg',
            brand:'Dhanpat Rai Publications',
            InStock:50,
            rating:5,
            reviews:48,
            description: 'Basically for advance level with more questions practices',
 
         },
        {
            name:'Maths',
            author:'R D Sharma',
            price:440,
            class:'VIII',
            image:'/images/rdviii.jpg',
            brand:'Dhanpat Rai Publications',
            InStock:100,
            rating:5,
            reviews:48,
            description: 'Basically for advance level with more questions practices',
 
         },
         {
            name:'Maths Step',
            author:'Asit Das Gupta, Surysbhushan Prasad',
            price:140,
            class:'I',
            image:'/images/msi.jpg',
            brand:'Bharti Bhawan',
            InStock:100,
            rating:5,
            reviews:190,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
         {
            name:'Maths Step',
            author:'Asit Das Gupta, Surysbhushan Prasad',
            price:150,
            class:'II',
            image:'/images/msii.jpg',
            brand:'Bharti Bhawan',
            InStock:300,
            rating:5,
            reviews:110,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
         {
            name:'Maths Step',
            author:'Asit Das Gupta, Surysbhushan Prasad',
            price:160,
            class:'III',
            image:'/images/msiii.jpg',
            brand:'Bharti Bhawan',
            InStock:160,
            rating:4.8,
            reviews:35,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
         {
            name:'Maths Step',
            author:'Asit Das Gupta, Surysbhushan Prasad',
            price:170,
            class:'IV',
            image:'/images/msiv.jpg',
            brand:'Bharti Bhawan',
            InStock:0,
            rating:4,
            reviews:55,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
         {
            name:'Maths Step',
            author:'Asit Das Gupta, Surysbhushan Prasad',
            price:180,
            class:'V',
            image:'/images/msv.jpg',
            brand:'Bharti Bhawan',
            InStock:300,
            rating:4.5,
            reviews:268,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
         {
            name:'Science',
            author:'A.C Shegal, Mukul Sehgal',
            price:499.00,
            class:'VI',
            image:'/images/rssvi.jpg',
            brand:'Ratna Sagar',
            InStock:20,
            rating:4,
            reviews:35,
            description: 'Best book for science and nicely written in organised manner',
 
         },
         {
            name:'Science',
            author:'A.C Shegal, Mukul Sehgal',
            price:509.00,
            class:'VII',
            image:'/images/rssvii.jpg',
            brand:'Ratna Sagar',
            InStock:25,
            rating:4.3,
            reviews:35,
            description: 'Best book for science and nicely written in organised manner',
 
         },
         {
            name:'Science',
            author:'A.C Shegal, Mukul Sehgal',
            price:550.00,
            class:'VIII',
            image:'/images/rssviii.jpg',
            brand:'Ratna Sagar',
            InStock:0,
            rating:4.8,
            reviews:35,
            description: 'Best book for science and nicely written in organised manner',
 
         },
         {
            name:'Social Science',
            author:'R.K Jain',
            price:499.90,
            class:'VI',
            image:'/images/rsssvi.jpg',
            brand:'Ratna Sagar',
            InStock:30,
            rating:4.5,
            reviews:55,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
         {
            name:'Social Science',
            author:'R.K.Jain',
            price:520.00,
            class:'VII',
            image:'/images/rssvi.jpg',
            brand:'Ratna Sagar',
            InStock:0,
            rating:4.5,
            reviews:68,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
         {
            name:'Social Science',
            author:'R.K.Jain',
            price:550,
            class:'VIII',
            image:'/images/rsssvi.jpg',
            brand:'Ratna Sagar',
            InStock:25,
            rating:4.5,
            reviews:45,
            description: 'Well Organised Mathematicals concepts and it covers basics to advance level',
 
         },
    ]
}

export default books;